# Learning NumPy


In [3624]:
import numpy as np

## The Basics

In [3625]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3626]:
b = np.array([[9.0,8.1,7],[5.5,3.8,11.7]])
print(b)

[[ 9.   8.1  7. ]
 [ 5.5  3.8 11.7]]


## Get Dimension of an Array

In [3627]:
a.ndim

1

In [3628]:
b.ndim

2

## Get Shape

In [3629]:
a.shape

(3,)

In [3630]:
b.shape

(2, 3)

## Get Type

In [3631]:
a.dtype

dtype('int64')

In [3632]:
b.dtype

dtype('float64')

In [3633]:
c = np.array([1,2,3,4], dtype = 'int8')
c.dtype

dtype('int8')

## Get Size

In [3634]:
a.itemsize

8

In [3635]:
b.itemsize

8

In [3636]:
c.itemsize

1

## Get Total Size

In [3637]:
a.size*a.itemsize

24

.size - total number of elements

In [3638]:
a.nbytes

24

In [3639]:
b.size * b.itemsize

48

In [3640]:
c.nbytes

4

# Accessing/Changing specific elements, rows, columns ...

In [3641]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


## Get a specific element [r,c]

In [3642]:
a[1,-2]

np.int64(13)

## Get a specific row

In [3643]:
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

## Get a specific column

In [3644]:
a[:,2]

array([ 3, 10])

## Getting more fancy  [startindex:endindex:stepsize]

In [3645]:
a[0,:-2:2]

array([1, 3, 5])

In [3646]:
b = a[:,::-1]
b

array([[ 7,  6,  5,  4,  3,  2,  1],
       [14, 13, 12, 11, 10,  9,  8]])

In [3647]:
b[1,3] = 300
b

array([[  7,   6,   5,   4,   3,   2,   1],
       [ 14,  13,  12, 300,  10,   9,   8]])

In [3648]:
a[:,2] = 133
a

array([[  1,   2, 133,   4,   5,   6,   7],
       [  8,   9, 133, 300,  12,  13,  14]])

## 3D example

In [3649]:
b = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Get a specific element (work outside in)

In [3650]:
print(b[0,1,0])

3


In [3651]:
b[1,:,0]

array([5, 7])

In [3652]:
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [3653]:
b[:,1,:] = [[103,104], [107,108]]
b

array([[[  1,   2],
        [103, 104]],

       [[  5,   6],
        [107, 108]]])

# Initializing Different Types of Arrays

## All 0s matrix

In [3654]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## All 1s matrix

In [3655]:
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

## Any other number

In [3656]:
np.full((2,2), 99, dtype= 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [3657]:
np.full(a.shape,31)

array([[31, 31, 31, 31, 31, 31, 31],
       [31, 31, 31, 31, 31, 31, 31]])

#### Using array's shape in full_like

In [3658]:
np.full_like(a,23)

array([[23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23]])

## Random decimal numbers

In [3659]:
np.random.rand(4,2)

array([[0.66355331, 0.69377173],
       [0.13474377, 0.43548729],
       [0.57157147, 0.78383084],
       [0.36290025, 0.01474366]])

In [3660]:
np.random.rand(3,3,2)

array([[[0.04577148, 0.12698504],
        [0.7971376 , 0.36412478],
        [0.64346412, 0.10572267]],

       [[0.1107067 , 0.65206028],
        [0.3725549 , 0.96813206],
        [0.33949964, 0.344568  ]],

       [[0.39612696, 0.26388184],
        [0.07753705, 0.18851018],
        [0.23225135, 0.38916096]]])

In [3661]:
np.random.random_sample(a.shape)

array([[0.24190258, 0.26072652, 0.87115067, 0.73497409, 0.95346806,
        0.1374643 , 0.15444243],
       [0.41518853, 0.94645799, 0.20992782, 0.20912322, 0.82075792,
        0.93137147, 0.14793275]])

## Random Integer values

In [3662]:
# Generates number from 0 to 6
print(np.random.randint(7))
# Generates number from 3 to 29
print(np.random.randint(3,30))

1
5


In [3663]:
np.random.randint(10,size=(3,3))

array([[9, 3, 1],
       [2, 6, 7],
       [2, 5, 6]])

## Identity Matrix

In [3664]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Repeating array

In [3665]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [3666]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Exercise

#### First Solution

In [3667]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3668]:
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [3669]:
arr[2,2] = 9
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Second Solution

In [3670]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3671]:
arr[::4,:] = 1
arr

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [3672]:
arr[:,::4] = 1
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [3673]:
arr[2,2] = 9
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Third Solution

In [3674]:
arr = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [3675]:
arr[1:-1,1:-1] = z
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Copying

In [3676]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [3677]:
b[0] = 100
a

array([100,   2,   3])

### To prevent this use copy method

In [3678]:
a = np.array([1,2,3])
b = a.copy()
b

array([1, 2, 3])

In [3679]:
b[0] = 100
a

array([1, 2, 3])

In [3680]:
a = np.array([[1,2],[3,4]])
b = a.copy()
b

array([[1, 2],
       [3, 4]])

In [3681]:
b[0,1] = 100
print(a)
print(b)

[[1 2]
 [3 4]]
[[  1 100]
 [  3   4]]


# Mathematics

## Basic arithmetic and functions

In [3682]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3683]:
a+2

array([3, 4, 5, 6])

In [3684]:
a-2

array([-1,  0,  1,  2])

In [3685]:
a*2

array([2, 4, 6, 8])

In [3686]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [3687]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [3688]:
a ** 2

array([ 1,  4,  9, 16])

In [3689]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [3690]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

## Linear Algebra

#### Matrix Multiplication

In [3691]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [3692]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

#### Find the determinant

In [3693]:
c = np.identity(3)
print(np.linalg.det(c))

1.0


## Statistics

In [3694]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [3695]:
np.min(stats)

np.int64(1)

#### Min for each column

In [3696]:
np.min(stats,axis=0)

array([1, 2, 3])

#### Min for each row

In [3697]:
np.min(stats,axis=1)

array([1, 4])

In [3698]:
np.max(stats)

np.int64(6)

In [3699]:
np.sum(stats)

np.int64(21)

In [3700]:
np.mean(stats)

np.float64(3.5)

# Reogranizing Arrays

In [3701]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before.shape

(2, 4)

In [3702]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [3703]:
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Vertically stacking Vectors

In [3704]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2+v1,v2-v1,v1*v2])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 6,  8, 10, 12],
       [ 4,  4,  4,  4],
       [ 5, 12, 21, 32]])

## Horizontal stack

In [3705]:
h1 = np.ones((2,4))
h2 = np.full((2,2),237)

np.hstack([h1,h2, h2 +7])

array([[  1.,   1.,   1.,   1., 237., 237., 244., 244.],
       [  1.,   1.,   1.,   1., 237., 237., 244., 244.]])

# Miscellaneous

## Load Data from File

In [3706]:
array = np.genfromtxt('data.txt', delimiter=',')
array

array([[  5.,   6.,   8., -11.,  37.],
       [  1.,   9.,   3.,   4.,   8.],
       [  5.,   6.,  -7.,   9.,   0.]])

In [3707]:
brray = array.astype('int32')
brray

array([[  5,   6,   8, -11,  37],
       [  1,   9,   3,   4,   8],
       [  5,   6,  -7,   9,   0]], dtype=int32)

In [3708]:
brray[0,1] = 777
brray

array([[  5, 777,   8, -11,  37],
       [  1,   9,   3,   4,   8],
       [  5,   6,  -7,   9,   0]], dtype=int32)

In [3709]:
array

array([[  5.,   6.,   8., -11.,  37.],
       [  1.,   9.,   3.,   4.,   8.],
       [  5.,   6.,  -7.,   9.,   0.]])

## Boolean Masking and Advanced Indexing

In [3710]:
array > 5

array([[False,  True,  True, False,  True],
       [False,  True, False, False,  True],
       [False,  True, False,  True, False]])

### You can index with a list in NumPy

In [3711]:
array[array > 5]

array([ 6.,  8., 37.,  9.,  8.,  6.,  9.])

In [3712]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[[1,2,8]]

array([2, 3, 9])

In [3713]:
# For each column returns True if any of it's element is greater than 5
np.any(array > 5, axis = 0)

array([False,  True,  True,  True,  True])

In [3714]:
np.all(array > 5, axis = 0)

array([False,  True, False, False, False])

In [3715]:
# For each row return True if all of it's elements are positive
np.all(array > 0, axis = 1)

array([False,  True, False])

In [3716]:
((array > 5) & (array < 10))

array([[False,  True,  True, False, False],
       [False,  True, False, False,  True],
       [False,  True, False,  True, False]])

In [3717]:
~(array>5)

array([[ True, False, False,  True, False],
       [ True, False,  True,  True, False],
       [ True, False,  True, False,  True]])

# Quiz


In [3718]:
z = np.array([[1,2,3,4,5]])
ar = z.repeat(6,axis=0)
for i in range(1,6):
    ar[i,:] += 5*i
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [3719]:
ar[2:4,:2]

array([[11, 12],
       [16, 17]])

In [3720]:
ar[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [3721]:
ar[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])